# Devenv repositories configuration
urlPrefix=git@github.com:metaborg

# Gradle plugins
gradle.config=true
gradle.config.branch=dependency-catalog
gradle.config.submodule=true

# Don't include Gitonium, as it bootstraps using a newer version of itself (>= Gitonium 1.7.0)
#  that is not yet compatible with this build of Spoofax 3, but replaces any other (older) Gitonium on the build
#  class path.
gitonium=false
gitonium.branch=master
gitonium.submodule=true
gitonium.update=true

# Exclude Coronium, it is not published with the other artifacts.
# Instead, publish Coronium separately and use a specific version.
coronium=false
coronium.branch=master
coronium.submodule=true
coronium.update=true


# Spoofax 2
# HACK: update but do not enable/include builds from several repositories. Those builds will be included by the releng
# composite build. When update is set to false, releng will not include those builds.
spoofax.gradle=false
spoofax.gradle.update=true
spoofax.gradle.branch=dependency-catalog
spoofax.gradle.submodule=true

mb-rep=false
mb-rep.update=true
mb-rep.branch=dependency-catalog
mb-rep.dir=mb.rep
mb-rep.submodule=true

mb-exec=false
mb-exec.update=true
mb-exec.branch=dependency-catalog
mb-exec.dir=mb.exec
mb-exec.submodule=true

jsglr=false
jsglr.update=true
jsglr.branch=dependency-catalog
jsglr.submodule=true

sdf=false
sdf.update=true
sdf.branch=dependency-catalog
sdf.submodule=true

stratego=false
stratego.update=true
stratego.branch=dependency-catalog
stratego.submodule=true

strategoxt=false
strategoxt.update=true
strategoxt.branch=dependency-catalog
strategoxt.submodule=true

esv=false
esv.update=true
esv.branch=dependency-catalog
esv.submodule=true

nabl=false
nabl.update=true
nabl.branch=dependency-catalog
nabl.submodule=true

spoofax2=false
spoofax2.update=true
spoofax2.branch=dependency-catalog
spoofax2.url=git@github.com:metaborg/spoofax
spoofax2.jenkinsjob=metaborg/spoofax
spoofax2.submodule=true

spt=false
spt.update=true
spt.branch=dependency-catalog
spt.submodule=true

# HACK: only releng should be enabled for builds; the releng included build includes all projects from the above
# Spoofax 2 repositories. This is done to prevent cyclic included builds, which Gradle does not support.
releng=true
releng.branch=dependency-catalog
releng.url=git@github.com:metaborg/spoofax-deploy
releng.jenkinsjob=metaborg/spoofax-deploy
releng.submodule=true


# Spoofax 3 and co.

log=true
log.branch=dependency-catalog
log.submodule=true

resource=true
resource.branch=dependency-catalog
resource.submodule=true

common=true
common.branch=dependency-catalog
common.submodule=true

pie=true
pie.branch=dependency-catalog
pie.submodule=true

spoofax-pie=true
spoofax-pie.branch=dependency-catalog
spoofax-pie.dir=spoofax.pie
spoofax-pie.submodule=true


# Continuous integration
jenkins.pipeline=false
jenkins.pipeline.branch=develop
jenkins.pipeline.submodule=true
