# Devenv repositories configuration
urlPrefix=git@github.com:metaborg

# Gradle plugins
gradle.config=false
gradle.config.branch=develop
gitonium=false
gitonium.branch=develop
coronium=false
coronium.branch=develop


# Spoofax 2
# HACK: update but do not enable/include builds from several repositories. Those builds will be included by the releng
# composite build. When update is set to false, releng will not include those builds.
spoofax.gradle=false
spoofax.gradle.update=true
spoofax.gradle.branch=code-completion

mb-rep=false
mb-rep.update=true
mb-rep.branch=code-completion
mb-rep.dir=mb.rep

mb-exec=false
mb-exec.update=true
mb-exec.branch=code-completion
mb-exec.dir=mb.exec

jsglr=false
jsglr.update=true
jsglr.branch=code-completion

sdf=false
sdf.update=true
sdf.branch=code-completion

stratego=false
stratego.update=true
stratego.branch=code-completion

strategoxt=false
strategoxt.update=true
strategoxt.branch=code-completion

esv=false
esv.update=true
esv.branch=code-completion

nabl=false
nabl.update=true
nabl.branch=code-completion

spoofax2=false
spoofax2.update=true
spoofax2.branch=code-completion
spoofax2.url=git@github.com:metaborg/spoofax
spoofax2.jenkinsjob=metaborg/spoofax

# HACK: only releng should be enabled for builds; the releng included build includes all projects from the above
# Spoofax 2 repositories. This is done to prevent cyclic included builds, which Gradle does not support.
releng=true
releng.branch=code-completion
releng.url=git@github.com:metaborg/spoofax-deploy
releng.jenkinsjob=metaborg/spoofax-deploy


# Spoofax 3 and co.
log=true
log.branch=code-completion
resource=true
resource.branch=code-completion
common=true
common.branch=develop
pie=true
pie.branch=code-completion
spoofax-pie=true
spoofax-pie.dir=spoofax.pie
spoofax-pie.branch=code-completion


# Continuous integration
jenkins.pipeline=false
