name: Build
on: workflow_dispatch
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2019, macos-10.15, macos-11 ]
        java: [ 11 ]
        gradle: [ 5.6.4, 6.9.1 ]
        experimental: [ false ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      # Increases page file size on Windows, fixing JVM crashes such as "The paging file is too small for this operation
      # to complete"
      - uses: al-cheb/configure-pagefile-action@v1.2
        if: runner.os == 'Windows'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        id: repo-update
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: -c repo.settings.gradle.kts update --transport https "-Dorg.gradle.jvmargs=-Xms5G -Xmx5G -Xss8M"
      - uses: actions/cache@v2
        id: cache-mavenize
        with:
          path: |
            ~/.mavenize/eclipse_archive_cache/*.dmg
            ~/.mavenize/eclipse_archive_cache/*.zip
            ~/.mavenize/eclipse_archive_cache/*.tar.gz
          key: mavenize-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            mavenize-${{ runner.os }}-
      - uses: actions/cache@v2
        id: cache-gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ matrix.gradle }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - uses: eskatos/gradle-command-action@v1
        id: build-all
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: buildAll --parallel --stacktrace "-Dorg.gradle.jvmargs=-Xms5G -Xmx5G -Xss8M"
      - id: print-jvm-crash-logs
        if: ${{ failure() }}
        run: cat hs_err_pid*.log; cat **/hs_err_pid*.log; cat replay_pid*.log; cat **/replay_pid*.log; true
        shell: bash {0}
