name: Build
on: workflow_dispatch
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2019, macos-10.15, macos-11 ]
        java: [ 11 ]
        gradle: [ 6.9.1 ]
        experimental: [ false ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      # Increases page file size on Windows, fixing JVM crashes such as "The paging file is too small for this operation
      # to complete"
      - id: increase-page-file-size-on-windows
        uses: al-cheb/configure-pagefile-action@v1.2
        if: runner.os == 'Windows'
      # Install coreutils via brew on macOS, needed to run sdf2table.
      - id: install-coreutils-on-macos
        if: runner.os == 'macOS'
        run: brew install coreutils
      # Setup docker on macOS, needed to run sdf2table.
      - id: setup-docker-on-macos
        uses: docker-practice/actions-setup-docker@master
        if: runner.os == 'macOS'
      # Checkout this Git repository.
      - id: checkout
        uses: actions/checkout@v2
      # Setup Java, adopt variant, according to the Java version from the matrix.
      - id: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      # Run Gradle (version from the matrix) with file repo.settings.gradle.kts to check out sub-repos.
      - id: repo-update
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: -c repo.settings.gradle.kts update --transport https "-Dorg.gradle.jvmargs=-Xms5G -Xmx5G -Xss8M"
      # Set up caching for the Coronium Gradle plugin
      - id: cache-mavenize
        uses: actions/cache@v2
        with:
          path: |
            ~/.mavenize/eclipse_archive_cache/*.dmg
            ~/.mavenize/eclipse_archive_cache/*.zip
            ~/.mavenize/eclipse_archive_cache/*.tar.gz
          key: mavenize-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            mavenize-${{ runner.os }}-
      # Set up caching for Gradle. TODO: is this still needed? Gradle action seems to do its own caching?
      - id: cache-gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ matrix.gradle }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      # Run the build (with Gradle version from the matrix).
      - id: build
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: buildAll --parallel --stacktrace "-Dorg.gradle.jvmargs=-Xms5G -Xmx5G -Xss8M"
      # Print JVM crash/replay logs if the previous step failed.
      - id: print-jvm-crash-logs
        if: ${{ failure() }}
        run: cat hs_err_pid*.log; cat **/hs_err_pid*.log; cat replay_pid*.log; cat **/replay_pid*.log; true
        shell: bash {0}
